/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatRoom = IDL.Variant({
  'VIP' : IDL.Null,
  'Premium' : IDL.Null,
  'Free' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'room' : IDL.Opt(ChatRoom),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
  'excerpt' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'contentUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'viewCount' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'isTrending' : IDL.Bool,
});
export const MembershipTier = IDL.Variant({
  'VIP' : IDL.Null,
  'Premium' : IDL.Null,
  'Free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'joinedAt' : IDL.Int,
  'tier' : MembershipTier,
  'avatarUrl' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'room' : ChatRoom,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'isPinned' : IDL.Bool,
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const ModerationAction = IDL.Variant({
  'DeleteMessage' : IDL.Null,
  'AutoFlagProfanity' : IDL.Null,
  'PinMessage' : IDL.Null,
  'AutoFlagLink' : IDL.Null,
  'AutoFlagScam' : IDL.Null,
  'AutoFlagSpam' : IDL.Null,
  'UnpinMessage' : IDL.Null,
  'MuteUser' : IDL.Null,
  'FlagSuspiciousActivity' : IDL.Null,
});
export const ModerationLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : ModerationAction,
  'targetPrincipal' : IDL.Opt(IDL.Principal),
  'targetMessageId' : IDL.Opt(IDL.Nat),
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
});
export const MutedUser = IDL.Record({
  'principal' : IDL.Principal,
  'mutedUntil' : IDL.Int,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  'addReaction' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'claimOwner' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createAnnouncement' : IDL.Func(
      [IDL.Opt(ChatRoom), IDL.Text],
      [IDL.Variant({ 'ok' : Announcement, 'err' : IDL.Text })],
      [],
    ),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
      [],
    ),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
      [],
    ),
  'deleteAnnouncement' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteBlogPost' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteMessage' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeUsersToday' : IDL.Nat,
          'totalMessages' : IDL.Nat,
          'totalProjects' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAnnouncements' : IDL.Func(
      [IDL.Opt(ChatRoom)],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPosts' : IDL.Func(
      [IDL.Opt(IDL.Bool)],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [ChatRoom, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getModerationLogs' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ModerationLog)],
      ['query'],
    ),
  'getMutedUsers' : IDL.Func([], [IDL.Vec(MutedUser)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getOnlineUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPinnedMessages' : IDL.Func([ChatRoom], [IDL.Vec(ChatMessage)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementProjectView' : IDL.Func([IDL.Nat], [], []),
  'isOwnerQuery' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserMuted' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'muteUser' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'pinMessage' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'publishBlogPost' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerOrUpdateUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'sendMessage' : IDL.Func(
      [ChatRoom, IDL.Text],
      [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
      [],
    ),
  'setMembershipTier' : IDL.Func(
      [IDL.Principal, MembershipTier],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setOwnerPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setProjectFeatured' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setProjectTrending' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unmuteUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unpinMessage' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
      [],
    ),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
      ],
      [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatRoom = IDL.Variant({
    'VIP' : IDL.Null,
    'Premium' : IDL.Null,
    'Free' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'room' : IDL.Opt(ChatRoom),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
    'excerpt' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'contentUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'viewCount' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'isTrending' : IDL.Bool,
  });
  const MembershipTier = IDL.Variant({
    'VIP' : IDL.Null,
    'Premium' : IDL.Null,
    'Free' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'joinedAt' : IDL.Int,
    'tier' : MembershipTier,
    'avatarUrl' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'room' : ChatRoom,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'isPinned' : IDL.Bool,
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const ModerationAction = IDL.Variant({
    'DeleteMessage' : IDL.Null,
    'AutoFlagProfanity' : IDL.Null,
    'PinMessage' : IDL.Null,
    'AutoFlagLink' : IDL.Null,
    'AutoFlagScam' : IDL.Null,
    'AutoFlagSpam' : IDL.Null,
    'UnpinMessage' : IDL.Null,
    'MuteUser' : IDL.Null,
    'FlagSuspiciousActivity' : IDL.Null,
  });
  const ModerationLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : ModerationAction,
    'targetPrincipal' : IDL.Opt(IDL.Principal),
    'targetMessageId' : IDL.Opt(IDL.Nat),
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  const MutedUser = IDL.Record({
    'principal' : IDL.Principal,
    'mutedUntil' : IDL.Int,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    'addReaction' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'claimOwner' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createAnnouncement' : IDL.Func(
        [IDL.Opt(ChatRoom), IDL.Text],
        [IDL.Variant({ 'ok' : Announcement, 'err' : IDL.Text })],
        [],
      ),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
        [],
      ),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
        [],
      ),
    'deleteAnnouncement' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteBlogPost' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteMessage' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeUsersToday' : IDL.Nat,
            'totalMessages' : IDL.Nat,
            'totalProjects' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAnnouncements' : IDL.Func(
        [IDL.Opt(ChatRoom)],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPosts' : IDL.Func(
        [IDL.Opt(IDL.Bool)],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [ChatRoom, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getModerationLogs' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ModerationLog)],
        ['query'],
      ),
    'getMutedUsers' : IDL.Func([], [IDL.Vec(MutedUser)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getOnlineUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPinnedMessages' : IDL.Func(
        [ChatRoom],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementProjectView' : IDL.Func([IDL.Nat], [], []),
    'isOwnerQuery' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserMuted' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'muteUser' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'pinMessage' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'publishBlogPost' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerOrUpdateUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'sendMessage' : IDL.Func(
        [ChatRoom, IDL.Text],
        [IDL.Variant({ 'ok' : ChatMessage, 'err' : IDL.Text })],
        [],
      ),
    'setMembershipTier' : IDL.Func(
        [IDL.Principal, MembershipTier],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setOwnerPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setProjectFeatured' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setProjectTrending' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unmuteUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unpinMessage' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text })],
        [],
      ),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };