/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'room' : [] | [ChatRoom],
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
  'excerpt' : string,
}
export interface ChatMessage {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'room' : ChatRoom,
  'sender' : Principal,
  'timestamp' : bigint,
  'senderName' : string,
  'isPinned' : boolean,
  'reactions' : Array<[string, bigint]>,
}
export type ChatRoom = { 'VIP' : null } |
  { 'Premium' : null } |
  { 'Free' : null };
export type MembershipTier = { 'VIP' : null } |
  { 'Premium' : null } |
  { 'Free' : null };
export type ModerationAction = { 'DeleteMessage' : null } |
  { 'AutoFlagProfanity' : null } |
  { 'PinMessage' : null } |
  { 'AutoFlagLink' : null } |
  { 'AutoFlagScam' : null } |
  { 'AutoFlagSpam' : null } |
  { 'UnpinMessage' : null } |
  { 'MuteUser' : null } |
  { 'FlagSuspiciousActivity' : null };
export interface ModerationLog {
  'id' : bigint,
  'action' : ModerationAction,
  'targetPrincipal' : [] | [Principal],
  'targetMessageId' : [] | [bigint],
  'timestamp' : bigint,
  'reason' : string,
}
export interface MutedUser {
  'principal' : Principal,
  'mutedUntil' : bigint,
  'reason' : string,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'contentUrl' : string,
  'createdAt' : bigint,
  'description' : string,
  'isFree' : boolean,
  'viewCount' : bigint,
  'isFeatured' : boolean,
  'category' : string,
  'isTrending' : boolean,
}
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'joinedAt' : bigint,
  'tier' : MembershipTier,
  'avatarUrl' : string,
}
export interface _SERVICE {
  'addReaction' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'claimOwner' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'createAnnouncement' : ActorMethod<
    [[] | [ChatRoom], string],
    { 'ok' : Announcement } |
      { 'err' : string }
  >,
  'createBlogPost' : ActorMethod<
    [string, string, string],
    { 'ok' : BlogPost } |
      { 'err' : string }
  >,
  'createProject' : ActorMethod<
    [string, string, string, string, string, boolean, boolean],
    { 'ok' : Project } |
      { 'err' : string }
  >,
  'deleteAnnouncement' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteBlogPost' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteMessage' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'deleteProject' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'activeUsersToday' : bigint,
      'totalMessages' : bigint,
      'totalProjects' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getAnnouncements' : ActorMethod<[[] | [ChatRoom]], Array<Announcement>>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPosts' : ActorMethod<[[] | [boolean]], Array<BlogPost>>,
  'getMessages' : ActorMethod<[ChatRoom, bigint], Array<ChatMessage>>,
  'getModerationLogs' : ActorMethod<[bigint], Array<ModerationLog>>,
  'getMutedUsers' : ActorMethod<[], Array<MutedUser>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getOnlineUserCount' : ActorMethod<[], bigint>,
  'getPinnedMessages' : ActorMethod<[ChatRoom], Array<ChatMessage>>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getProjects' : ActorMethod<[[] | [string], [] | [boolean]], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementProjectView' : ActorMethod<[bigint], undefined>,
  'isOwnerQuery' : ActorMethod<[], boolean>,
  'isUserMuted' : ActorMethod<[Principal], boolean>,
  'muteUser' : ActorMethod<
    [Principal, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'pinMessage' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'publishBlogPost' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'registerOrUpdateUser' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'sendMessage' : ActorMethod<
    [ChatRoom, string],
    { 'ok' : ChatMessage } |
      { 'err' : string }
  >,
  'setMembershipTier' : ActorMethod<
    [Principal, MembershipTier],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setOwnerPrincipal' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setProjectFeatured' : ActorMethod<
    [bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setProjectTrending' : ActorMethod<
    [bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unmuteUser' : ActorMethod<[Principal], { 'ok' : null } | { 'err' : string }>,
  'unpinMessage' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string],
    { 'ok' : BlogPost } |
      { 'err' : string }
  >,
  'updateProject' : ActorMethod<
    [bigint, string, string, string, string, string, boolean, boolean],
    { 'ok' : Project } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];