/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    isPublished: boolean;
    createdAt: bigint;
    excerpt: string;
}
export interface MutedUser {
    principal: Principal;
    mutedUntil: bigint;
    reason: string;
}
export interface Announcement {
    id: bigint;
    content: string;
    createdAt: bigint;
    room?: ChatRoom;
}
export interface ChatMessage {
    id: bigint;
    isDeleted: boolean;
    content: string;
    room: ChatRoom;
    sender: Principal;
    timestamp: bigint;
    senderName: string;
    isPinned: boolean;
    reactions: Array<[string, bigint]>;
}
export interface ModerationLog {
    id: bigint;
    action: ModerationAction;
    targetPrincipal?: Principal;
    targetMessageId?: bigint;
    timestamp: bigint;
    reason: string;
}
export interface Project {
    id: bigint;
    title: string;
    thumbnailUrl: string;
    contentUrl: string;
    createdAt: bigint;
    description: string;
    isFree: boolean;
    viewCount: bigint;
    isFeatured: boolean;
    category: string;
    isTrending: boolean;
}
export interface UserProfile {
    principal: Principal;
    username: string;
    joinedAt: bigint;
    tier: MembershipTier;
    avatarUrl: string;
}
export enum MembershipTier {
    VIP = "VIP",
    Premium = "Premium",
    Free = "Free"
}
export enum ModerationAction {
    DeleteMessage = "DeleteMessage",
    AutoFlagProfanity = "AutoFlagProfanity",
    PinMessage = "PinMessage",
    AutoFlagLink = "AutoFlagLink",
    AutoFlagScam = "AutoFlagScam",
    AutoFlagSpam = "AutoFlagSpam",
    UnpinMessage = "UnpinMessage",
    MuteUser = "MuteUser",
    FlagSuspiciousActivity = "FlagSuspiciousActivity"
}
export interface backendInterface {
    addReaction(messageId: bigint, emoji: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    claimOwner(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createAnnouncement(room: ChatRoom | null, content: string): Promise<{
        __kind__: "ok";
        ok: Announcement;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createBlogPost(title: string, content: string, excerpt: string): Promise<{
        __kind__: "ok";
        ok: BlogPost;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createProject(title: string, description: string, category: string, thumbnailUrl: string, contentUrl: string, isFree: boolean, isFeatured: boolean): Promise<{
        __kind__: "ok";
        ok: Project;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteAnnouncement(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteBlogPost(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteMessage(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteProject(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAnalytics(): Promise<{
        activeUsersToday: bigint;
        totalMessages: bigint;
        totalProjects: bigint;
        totalUsers: bigint;
    }>;
    getAnnouncements(room: ChatRoom | null): Promise<Array<Announcement>>;
    getBlogPost(id: bigint): Promise<BlogPost | null>;
    getBlogPosts(published: boolean | null): Promise<Array<BlogPost>>;
    getMessages(room: ChatRoom, limit: bigint): Promise<Array<ChatMessage>>;
    getModerationLogs(limit: bigint): Promise<Array<ModerationLog>>;
    getMutedUsers(): Promise<Array<MutedUser>>;
    getMyProfile(): Promise<UserProfile | null>;
    getOnlineUserCount(): Promise<bigint>;
    getPinnedMessages(room: ChatRoom): Promise<Array<ChatMessage>>;
    getProject(id: bigint): Promise<Project | null>;
    getProjects(category: string | null, featured: boolean | null): Promise<Array<Project>>;
    getUserProfile(p: Principal): Promise<UserProfile | null>;
    incrementProjectView(id: bigint): Promise<void>;
    isOwnerQuery(): Promise<boolean>;
    isUserMuted(p: Principal): Promise<boolean>;
    muteUser(target: Principal, durationSecs: bigint, reason: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    pinMessage(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    publishBlogPost(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerOrUpdateUser(username: string, avatarUrl: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendMessage(room: ChatRoom, content: string): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setMembershipTier(target: Principal, tier: MembershipTier): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setOwnerPrincipal(newOwner: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setProjectFeatured(id: bigint, featured: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setProjectTrending(id: bigint, trending: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unmuteUser(target: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unpinMessage(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateBlogPost(id: bigint, title: string, content: string, excerpt: string): Promise<{
        __kind__: "ok";
        ok: BlogPost;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateProject(id: bigint, title: string, description: string, category: string, thumbnailUrl: string, contentUrl: string, isFree: boolean, isFeatured: boolean): Promise<{
        __kind__: "ok";
        ok: Project;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Announcement as _Announcement, BlogPost as _BlogPost, ChatMessage as _ChatMessage, ChatRoom as _ChatRoom, MembershipTier as _MembershipTier, ModerationAction as _ModerationAction, ModerationLog as _ModerationLog, Project as _Project, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addReaction(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimOwner(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.claimOwner();
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimOwner();
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAnnouncement(arg0: ChatRoom | null, arg1: string): Promise<{
        __kind__: "ok";
        ok: Announcement;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBlogPost(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: BlogPost;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0, arg1, arg2);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0, arg1, arg2);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean, arg6: boolean): Promise<{
        __kind__: "ok";
        ok: Project;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnnouncement(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMessage(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<{
        activeUsersToday: bigint;
        totalMessages: bigint;
        totalProjects: bigint;
        totalUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getAnnouncements(arg0: ChatRoom | null): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncements(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncements(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: bigint): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPosts(arg0: boolean | null): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMessages(arg0: ChatRoom, arg1: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(to_candid_ChatRoom_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(to_candid_ChatRoom_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModerationLogs(arg0: bigint): Promise<Array<ModerationLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModerationLogs(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModerationLogs(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMutedUsers(): Promise<Array<MutedUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMutedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMutedUsers();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnlineUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnlineUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnlineUserCount();
            return result;
        }
    }
    async getPinnedMessages(arg0: ChatRoom): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedMessages(to_candid_ChatRoom_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedMessages(to_candid_ChatRoom_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(arg0: string | null, arg1: boolean | null): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementProjectView(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementProjectView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementProjectView(arg0);
            return result;
        }
    }
    async isOwnerQuery(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOwnerQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOwnerQuery();
            return result;
        }
    }
    async isUserMuted(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserMuted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserMuted(arg0);
            return result;
        }
    }
    async muteUser(arg0: Principal, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.muteUser(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.muteUser(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async pinMessage(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.pinMessage(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinMessage(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishBlogPost(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.publishBlogPost(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishBlogPost(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerOrUpdateUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrUpdateUser(arg0, arg1);
                return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrUpdateUser(arg0, arg1);
            return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: ChatRoom, arg1: string): Promise<{
        __kind__: "ok";
        ok: ChatMessage;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(to_candid_ChatRoom_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(to_candid_ChatRoom_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async setMembershipTier(arg0: Principal, arg1: MembershipTier): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setMembershipTier(arg0, to_candid_MembershipTier_n35(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMembershipTier(arg0, to_candid_MembershipTier_n35(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setOwnerPrincipal(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setOwnerPrincipal(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOwnerPrincipal(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProjectFeatured(arg0: bigint, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setProjectFeatured(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProjectFeatured(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProjectTrending(arg0: bigint, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setProjectTrending(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProjectTrending(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async unmuteUser(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unmuteUser(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmuteUser(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async unpinMessage(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinMessage(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinMessage(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBlogPost(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: BlogPost;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean, arg7: boolean): Promise<{
        __kind__: "ok";
        ok: Project;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Announcement_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ChatRoom_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatRoom): ChatRoom {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipTier_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipTier): MembershipTier {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ModerationAction_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModerationAction): ModerationAction {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ModerationLog_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModerationLog): ModerationLog {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatRoom]): ChatRoom | null {
    return value.length === 0 ? null : from_candid_ChatRoom_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    username: string;
    joinedAt: bigint;
    tier: _MembershipTier;
    avatarUrl: string;
}): {
    principal: Principal;
    username: string;
    joinedAt: bigint;
    tier: MembershipTier;
    avatarUrl: string;
} {
    return {
        principal: value.principal,
        username: value.username,
        joinedAt: value.joinedAt,
        tier: from_candid_MembershipTier_n16(_uploadFile, _downloadFile, value.tier),
        avatarUrl: value.avatarUrl
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isDeleted: boolean;
    content: string;
    room: _ChatRoom;
    sender: Principal;
    timestamp: bigint;
    senderName: string;
    isPinned: boolean;
    reactions: Array<[string, bigint]>;
}): {
    id: bigint;
    isDeleted: boolean;
    content: string;
    room: ChatRoom;
    sender: Principal;
    timestamp: bigint;
    senderName: string;
    isPinned: boolean;
    reactions: Array<[string, bigint]>;
} {
    return {
        id: value.id,
        isDeleted: value.isDeleted,
        content: value.content,
        room: from_candid_ChatRoom_n9(_uploadFile, _downloadFile, value.room),
        sender: value.sender,
        timestamp: value.timestamp,
        senderName: value.senderName,
        isPinned: value.isPinned,
        reactions: value.reactions
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    action: _ModerationAction;
    targetPrincipal: [] | [Principal];
    targetMessageId: [] | [bigint];
    timestamp: bigint;
    reason: string;
}): {
    id: bigint;
    action: ModerationAction;
    targetPrincipal?: Principal;
    targetMessageId?: bigint;
    timestamp: bigint;
    reason: string;
} {
    return {
        id: value.id,
        action: from_candid_ModerationAction_n26(_uploadFile, _downloadFile, value.action),
        targetPrincipal: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.targetPrincipal)),
        targetMessageId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.targetMessageId)),
        timestamp: value.timestamp,
        reason: value.reason
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    createdAt: bigint;
    room: [] | [_ChatRoom];
}): {
    id: bigint;
    content: string;
    createdAt: bigint;
    room?: ChatRoom;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        room: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.room))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    VIP: null;
} | {
    Premium: null;
} | {
    Free: null;
}): MembershipTier {
    return "VIP" in value ? MembershipTier.VIP : "Premium" in value ? MembershipTier.Premium : "Free" in value ? MembershipTier.Free : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BlogPost;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BlogPost;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Project;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Project;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DeleteMessage: null;
} | {
    AutoFlagProfanity: null;
} | {
    PinMessage: null;
} | {
    AutoFlagLink: null;
} | {
    AutoFlagScam: null;
} | {
    AutoFlagSpam: null;
} | {
    UnpinMessage: null;
} | {
    MuteUser: null;
} | {
    FlagSuspiciousActivity: null;
}): ModerationAction {
    return "DeleteMessage" in value ? ModerationAction.DeleteMessage : "AutoFlagProfanity" in value ? ModerationAction.AutoFlagProfanity : "PinMessage" in value ? ModerationAction.PinMessage : "AutoFlagLink" in value ? ModerationAction.AutoFlagLink : "AutoFlagScam" in value ? ModerationAction.AutoFlagScam : "AutoFlagSpam" in value ? ModerationAction.AutoFlagSpam : "UnpinMessage" in value ? ModerationAction.UnpinMessage : "MuteUser" in value ? ModerationAction.MuteUser : "FlagSuspiciousActivity" in value ? ModerationAction.FlagSuspiciousActivity : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ChatMessage;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ChatMessage;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ChatMessage_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Announcement;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Announcement;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Announcement_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ModerationLog>): Array<ModerationLog> {
    return value.map((x)=>from_candid_ModerationLog_n24(_uploadFile, _downloadFile, x));
}
function to_candid_ChatRoom_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRoom): _ChatRoom {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipTier_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): _MembershipTier {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRoom | null): [] | [_ChatRoom] {
    return value === null ? candid_none() : candid_some(to_candid_ChatRoom_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): {
    VIP: null;
} | {
    Premium: null;
} | {
    Free: null;
} {
    return value == MembershipTier.VIP ? {
        VIP: null
    } : value == MembershipTier.Premium ? {
        Premium: null
    } : value == MembershipTier.Free ? {
        Free: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
